object frmFuncionario: TfrmFuncionario
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'Funcion'#225'rio'
  ClientHeight = 671
  ClientWidth = 1014
  Color = clWindow
  Ctl3D = False
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlFundo: TPanel
    Left = 0
    Top = 0
    Width = 1014
    Height = 671
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitLeft = 160
    ExplicitTop = 144
    ExplicitWidth = 185
    ExplicitHeight = 41
    object pnlTitle: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 1008
      Height = 41
      Align = alTop
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = 'Funcionarios e dependentes'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      ExplicitLeft = 0
      ExplicitTop = 0
      ExplicitWidth = 767
    end
    object pnlRodape: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 638
      Width = 1008
      Height = 30
      Align = alBottom
      BevelOuter = bvNone
      BorderStyle = bsSingle
      Caption = 'Rodape'
      TabOrder = 1
      ExplicitTop = 432
      ExplicitWidth = 761
    end
    object pnlListaFunc: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 50
      Width = 734
      Height = 582
      Align = alClient
      BevelOuter = bvNone
      BorderStyle = bsSingle
      TabOrder = 2
      ExplicitWidth = 430
      ExplicitHeight = 376
      object pnlAcaoFunc: TPanel
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 726
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Button1: TButton
          AlignWithMargins = True
          Left = 646
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 0
          ExplicitLeft = 624
          ExplicitTop = 8
          ExplicitHeight = 25
        end
        object Button2: TButton
          AlignWithMargins = True
          Left = 403
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 1
          ExplicitLeft = 624
          ExplicitTop = 8
          ExplicitHeight = 25
        end
        object Button3: TButton
          AlignWithMargins = True
          Left = 484
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 2
          ExplicitLeft = 624
          ExplicitTop = 8
          ExplicitHeight = 25
        end
        object Button4: TButton
          AlignWithMargins = True
          Left = 565
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 3
          ExplicitLeft = 624
          ExplicitTop = 8
          ExplicitHeight = 25
        end
      end
      object DBGrid1: TDBGrid
        AlignWithMargins = True
        Left = 3
        Top = 85
        Width = 726
        Height = 492
        Align = alClient
        TabOrder = 1
        TitleFont.Charset = DEFAULT_CHARSET
        TitleFont.Color = clWindowText
        TitleFont.Height = -11
        TitleFont.Name = 'Tahoma'
        TitleFont.Style = []
      end
      object pnlManDadosFunc: TPanel
        AlignWithMargins = True
        Left = 3
        Top = 44
        Width = 726
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 2
        object Button5: TButton
          AlignWithMargins = True
          Left = 646
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 0
          ExplicitLeft = 624
          ExplicitTop = 8
          ExplicitHeight = 25
        end
        object Button6: TButton
          AlignWithMargins = True
          Left = 484
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 1
          ExplicitLeft = 582
          ExplicitTop = 0
          ExplicitHeight = 39
        end
        object Button7: TButton
          AlignWithMargins = True
          Left = 565
          Top = 3
          Width = 75
          Height = 27
          Align = alRight
          Caption = 'Button1'
          TabOrder = 2
          ExplicitLeft = 582
          ExplicitTop = 0
          ExplicitHeight = 39
        end
      end
    end
    object pnlDependentes: TPanel
      AlignWithMargins = True
      Left = 743
      Top = 50
      Width = 268
      Height = 582
      Align = alRight
      BevelOuter = bvNone
      BorderStyle = bsSingle
      TabOrder = 3
      ExplicitLeft = 496
      ExplicitHeight = 376
    end
  end
end
